#!/bin/bash

set -v
javac *.java


pkill rmiregistry
\rm -rf tProductor tProductargent tProductbronze tClient 
mkdir tProductor
mkdir tProductargent
mkdir tProductbronze


mkdir tClient

for i in Client ClientImpl ProductImpl Product_thread Product Client_thread
do  cp $i.class tClient ; done

for i in Productor ProductImpl Product Product_thread
do  cp $i.class tProductor ; done

for i in Productargent ProductImpl Product Product_thread
do  cp $i.class tProductargent ; done

for i in Productbronze ProductImpl Product  Product_thread
do  cp $i.class tProductbronze ; done

cd tProductor
rmiregistry 6666 &
cd ..

\rm *.class
