#!/bin/bash

if [ $# != 14 ]
then
        echo "Usage : $0 nbclindiv nbclcoop nbclvoleur nbclprudent nbclcoopmalin nbproductor nbproductargent nbproductbronze ordonnancement humain epuisable observation vol fin"
				exit -1
fi

set -v

javac *.java




mkdir tProductor
mkdir tProductargent
mkdir tProductbronze
mkdir tCoordinateur
mkdir tClient

for i in Client Clienttype ClientImpl Client_log_thread ProductImpl Product_thread Product Client_thread Personnalite Coordinateur Coordinateurtype CoordinateurImpl Tache
do  cp $i.class tClient ; done

for i in Coordinateur Coordinateurtype CoordinateurImpl Client Clienttype ClientImpl ProductImpl Product_thread Product Client_thread Personnalite Tache
do  cp $i.class tCoordinateur ; done

for i in Productor ProductImpl Product Product_thread
do  cp $i.class tProductor ; done

for i in Productargent ProductImpl Product Product_thread
do  cp $i.class tProductargent ; done

for i in Productbronze ProductImpl Product  Product_thread
do  cp $i.class tProductbronze ; done

cd tClient
rmiregistry 6666 &
cd ..

cd tProductor
xterm -hold -e  java Productor 6666 ${11} &
cd ..

cd tProductargent
xterm -hold -e  java Productargent 6666 ${11} &
cd ..

cd tProductbronze
xterm -hold -e  java Productbronze 6666 ${11} &
cd ..


sleep 1

cd tClient

let "tot=$1 + $2 + $3 + $4 + $5"
for i in $(seq 1 $1)
do
  xterm -hold -e java Clienttype localhost 6666 $i INDIVIDUALISTE $tot ${12} ${13} &
done

for i in $(seq 1 $2)
do
  let "no=$1 + $i"
  xterm -hold -e java Clienttype localhost 6666 $no COOPERATIF $tot ${12} ${13} &
done

for i in $(seq 1 $3)
do
  let "no=$1 + $2 + $i"
  xterm -hold -e java Clienttype localhost 6666 $no VOLEUR $tot ${12} ${13} &
done

for i in $(seq 1 $4)
do
  let "no=$1 + $2 + $3 + $i"
  xterm -hold -e java Clienttype localhost 6666 $no PRUDENT $tot ${12} ${13} &
done

for i in $(seq 1 $5)
do
  let "no=$1 + $2 + $3 + $4 + $i"
  xterm -hold -e java Clienttype localhost 6666 $no COOPERATIFMALIN $tot ${12} ${13} &
done

cd ..





sleep 1

cd tCoordinateur
xterm -hold -e  java Coordinateurtype 6666 $tot $9 ${10} ${14} &
cd ..
